services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - GIN_MODE=release
    volumes:
      - ./stocks.json:/root/stocks.json